
#ifndef __COMPRESS_H__
#define __COMPRESS_H__

enum compress_type_e
{
	UPLOAD_COMPRESS_GZ,
//	UPLOAD_COMPRESS_BZ,
//	UPLOAD_COMPRESS_BZ2,
	UPLOAD_COMPRESS_Z,
	UPLOAD_COMPRESS_ZIP,
	
	UPLOAD_COMPRESS_7Z,
	UPLOAD_COMPRESS_LZMA,
	UPLOAD_COMPRESS_TAR,
	UPLOAD_COMPRESS_TGZ,
	UPLOAD_COMPRESS_TAR_GZ,
	
	UPLOAD_COMPRESS_TAR_BZ,
	UPLOAD_COMPRESS_TAR_BZ2,
	UPLOAD_COMPRESS_TAR_Z,
	UPLOAD_COMPRESS_MAX
};


int do_compress(int type, char *buff, int buff_size, char * DestName, char *SrcName);
#endif
